# .sops.yaml
creation_rules:
  - path_regex: \w+.env
    encrypted_regex: "^(SERVER_SECRET|CLOUDFLARE)\\w*$"
    key_groups:
      - age:
          - age1hasavauxmejevz4kx9mn8cynj09675l9hhtsswkqr806mm97hpgsc67csu
